version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
    timezone: Europe/Vienna
  labels:
  - "dependencies"
  commit-message:
    prefix: deps
    include: scope

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '08:00'
    timezone: Europe/Vienna
  labels:
  - "CI/CD"
  commit-message:
    prefix: ci
    include: scope